name: replicator

services:
  rabbitmq:
    container_name: replicator-rabbitmq
    image: rabbitmq:4.1.4-management-alpine
    volumes:
    - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "15673:15672"
      - "5673:5672"

  discord-bot:
    container_name: replicator-discord-bot
    network_mode: host
    build:
      args:
        - APP_ENV=dev
      dockerfile: ./docker/discord/Dockerfile
    volumes:
      - ./:/app
    restart: always
    depends_on:
      - rabbitmq
      - mongo

  telegram-bot:
    container_name: replicator-telegram-bot
    network_mode: host
    build:
      args:
        - APP_ENV=dev
      dockerfile: ./docker/telegram/Dockerfile
    volumes:
      - ./:/app
    restart: always
    depends_on:
      - rabbitmq
      - mongo

  mongo:
    image: mongo:7.0.9-jammy
    container_name: replicator-mongo
    restart: always
    ports:
      - "27019:27017"
    volumes:
      - mongo_data:/data/db
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M

volumes:
  mongo_data:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  nats_network:
